const memories=[
{name:"Metro Card",note:"moving through the city"},{name:"Coffee Stain",note:"warmth, a pause"},{name:"Small Stone",note:"heavy in my pocket"},{name:"Key",note:"a door, for a while"},{name:"Photo Strip",note:"faces that stayed"},{name:"Dried Leaf",note:"quiet from the park"},{name:"Sticky Note",note:"small but important"},{name:"Receipt",note:"a moment I might forget"},{name:"Perfume",note:"a scene returning as smell"},{name:"Red String",note:"an invisible connection"},{name:"Face Covering",note:"protection, habit"},{name:"Concert Ticket",note:"a night that changed speed"},{name:"Crumpled Paper",note:"a thought I did not keep"},{name:"Coin",note:"small change, many times"},{name:"Paper Clip",note:"holding fragments together"},{name:"Pencil",note:"unfinished thoughts"},{name:"Bus Ticket",note:"a short ride"},{name:"Empty Pocket",note:"something lost, or never had"}
];
const sequences=[[17,2,3],[0,1,4],[11,13,7],[5,10,15],[9,14,12],[16,8,6]];
const pockets=[...document.querySelectorAll('.pocket')],table=document.getElementById('memoryTable'),template=document.getElementById('memoryTemplate'),placeholder=document.getElementById('tablePlaceholder'),progress=document.getElementById('progressText'),title=document.getElementById('memoryTitle'),description=document.getElementById('memoryDescription'),play=document.getElementById('startPerformance'),clear=document.getElementById('resetAll'),sound=document.getElementById('soundToggle');
let revealed=0,timer=null,soundOn=true,active=null,offset={x:0,y:0};
const sprite=i=>`${(i%5)*25}% ${Math.floor(i/5)*(100/3)}%`;
function tone(i){if(!soundOn)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=155+i*9;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.025,c.currentTime+.035);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.48);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.5);o.addEventListener('ended',()=>c.close())}
function position(piece){return{x:Math.random()*Math.max(0,table.clientWidth-piece.offsetWidth),y:Math.random()*Math.max(0,table.clientHeight-piece.offsetHeight)}}
function show(i){title.textContent=memories[i].name.toLowerCase();description.textContent=memories[i].note}
function reveal(i){if(table.querySelector(`[data-memory-index="${i}"]`))return;placeholder.hidden=true;const m=memories[i],piece=template.content.firstElementChild.cloneNode(true);piece.dataset.memoryIndex=i;piece.style.setProperty('--r',`${(Math.random()*7-3.5).toFixed(1)}deg`);piece.querySelector('.cutout').style.backgroundPosition=sprite(i);piece.querySelector('.label').textContent=m.name;piece.querySelector('.note').textContent=m.note;table.appendChild(piece);const p=position(piece);piece.style.left=`${p.x}px`;piece.style.top=`${p.y}px`;piece.addEventListener('pointerdown',begin);piece.addEventListener('click',()=>show(i));revealed++;progress.textContent=`${revealed} / ${memories.length}`;show(i);tone(i)}
function openPocket(button){if(button.classList.contains('opened'))return;button.classList.add('opened');sequences[Number(button.dataset.pocket)].forEach((i,n)=>setTimeout(()=>reveal(i),n*520))}
function begin(e){if(e.button!==0)return;active=e.currentTarget;const r=active.getBoundingClientRect();offset.x=e.clientX-r.left;offset.y=e.clientY-r.top;active.classList.add('dragging');active.setPointerCapture(e.pointerId);active.addEventListener('pointermove',move);active.addEventListener('pointerup',end,{once:true})}
function move(e){if(!active)return;const r=table.getBoundingClientRect(),x=Math.min(Math.max(0,e.clientX-r.left-offset.x),table.clientWidth-active.offsetWidth),y=Math.min(Math.max(0,e.clientY-r.top-offset.y),table.clientHeight-active.offsetHeight);active.style.left=`${x}px`;active.style.top=`${y}px`}
function end(e){if(!active)return;active.releasePointerCapture(e.pointerId);active.removeEventListener('pointermove',move);active.classList.remove('dragging');active=null}
function reset(announce=true){if(timer)clearInterval(timer);timer=null;document.body.classList.remove('performance-running');table.querySelectorAll('.memory-piece').forEach(p=>p.remove());pockets.forEach(p=>p.classList.remove('opened'));placeholder.hidden=false;revealed=0;progress.textContent=`0 / ${memories.length}`;play.disabled=false;play.textContent='play';if(announce){title.textContent='closed';description.textContent='Rearrange them as you remember.'}}
function start(){reset(false);document.body.classList.add('performance-running');play.disabled=true;play.textContent='playing';title.textContent='opening';description.textContent='';let i=0;openPocket(pockets[i++]);timer=setInterval(()=>{if(i>=pockets.length){clearInterval(timer);timer=null;document.body.classList.remove('performance-running');play.disabled=false;play.textContent='replay';title.textContent='open';description.textContent='Rearrange them as you remember.';return}openPocket(pockets[i++])},2300)}
pockets.forEach(p=>p.addEventListener('click',()=>openPocket(p)));play.addEventListener('click',start);clear.addEventListener('click',()=>reset(true));sound.addEventListener('click',()=>{soundOn=!soundOn;sound.textContent=soundOn?'sound':'muted';sound.setAttribute('aria-pressed',String(soundOn))});window.addEventListener('resize',()=>table.querySelectorAll('.memory-piece').forEach(p=>{p.style.left=`${Math.max(0,Math.min(parseFloat(p.style.left)||0,table.clientWidth-p.offsetWidth))}px`;p.style.top=`${Math.max(0,Math.min(parseFloat(p.style.top)||0,table.clientHeight-p.offsetHeight))}px`}));